### ISSUE TITLE
Can't click on an object inside a cell

### ISSUE THREAD

**Issue by vadurk** [imbus/robotframework-robosapiens#25]
Hello,

I'm having similar issue which was described in: https://github.com/imbus/robotframework-robosapiens/issues/7

I can't click on the following element "Rel...":

![Image](https://github.com/user-attachments/assets/570121de-9a98-45aa-b57d-874920aa4658)

What I tried:

Select Cell  1  Rel...  (it finds and selects the cell)
Press Key Combination  Enter  (nothing happens when I push Enter)

Double-click Cell   1  Rel...  (it double clicks the cell but nothing happens)

In reality this element is activated by a single click.

Edit:

I noticed that: when I hovered over a table element (while cell was selected) and then pressed Enter it worked.
But I guess hover over -> press enter = single click in this case..

Also tried to record with Scripting Tracker so the "clickCurrentCell" is performed on GuiGridView element, is it possible to introduce it to RoboSAPiens?
From SAP GUI Scripting API documentation:

![Image](https://github.com/user-attachments/assets/02a94ade-988a-46d7-82c5-6e623c397398)

**Comment by mardukbp** [comment]
Tables of type GridView (ALV Grid) have their own PressEnter Method and it wasn't being used. I just released version 2.16.4 which fixes this. Try again Select Cell followed by Press Key Combination.

**Comment by vadurk** [comment]
With version 2.16.4 the old "bug" is back where "Press Key Combination  Enter" doesn't refresh the new elements which have appeared in window after pushing it. Can you take a look?

**Comment by mardukbp** [comment]
> With version 2.16.4 the old "bug" is back where "Press Key Combination Enter" doesn't refresh the new elements

I changed the behavior so that the elements are not refreshed when pressing Enter is forwarded to the table. But I will revert it.

> "clickCurrentCell" is performed on GuiGridView element, is it possible to introduce it to RoboSAPiens?

Yes. That will require a new keyword. I will implement it next week.

**Comment by vadurk** [comment]
I have made myself a workaround till the keyword is implemented :)

![Image](https://github.com/user-attachments/assets/4c4f7f04-7498-4bc8-93e1-7d8b8a525c3f)

Not sure if F5 is used in SAP anywhere but at least I can confirm that `ClickCurrentCell()` solved the issue.

**Comment by mardukbp** [comment]
Yes, I will implement it. I have been suffering from headaches the whole month. I am actually on sick leave. I do what I can when I can. Thank you for your patience and also thank you for helping solve other issues. I appreciate it :)

**Comment by vadurk** [comment]
> Yes, I will implement it. I have been suffering from headaches the whole month. I am actually on sick leave. I do what I can when I can. Thank you for your patience and also thank you for helping solve other issues. I appreciate it :)

Sorry to hear that man.. I hope you're well. I didn't want to sound pushy or anything. I really appreciate the work you're doing with this project, I really want to use it and make it better for everyone :) Take you're time, health > anything else.

**Comment by mardukbp** [comment]
I just published version 2.16.6. Select Cell now uses ClickCurrentCell. I hope it works :)

**Comment by vadurk** [comment]
I just tested version 2.16.6. Sadly but it's not working.
I see that Select cell tries to click the cell but it's still not clicked. 
As I wrote above what actually worked for me was biding a button to ClickCurrentCell and pushing it.

**Comment by mardukbp** [comment]
I think the problem is that I do not know the cell type. But you can help me :)

With Scripting Tracker get the ID of the GuiGridView and then use the tab DumpState to get the ID of the column:

![Image](https://github.com/user-attachments/assets/0432aff0-5843-4967-9e6d-133edf4f115d)

Then use the column ID in the field InnerObject to find out the cell type:

![Image](https://github.com/user-attachments/assets/4cfb01d9-20bf-46fb-b927-d9f67758b5cd)

**Comment by vadurk** [comment]
This?

![Image](https://github.com/user-attachments/assets/01df6d93-6cb6-4f34-80c2-8b2538403d5a)

**Comment by mardukbp** [comment]
The cell type is independent from the column name. There are only 5 cell types. Normal is a text cell. I tried calling ClickCurrentCell on a text cell that does not have an icon and got an exception. I just released version 2.16.8 which checks if the cell has an icon and if it does it calls ClickCurrentCell. Hopefully it works :)

**Comment by vadurk** [comment]
I've tested with version 2.16.8 and it works! Thanks a lot!
